### ISSUE TITLE
Progress bar?

### ISSUE THREAD

**Issue by Deleetdk** [statistikat/VIM#10]
As you point out in [your 2016 VIM paper](https://www.researchgate.net/profile/Matthias_Templ/publication/309336197_Imputation_with_the_R_package_VIM/links/580b490a08ae2cb3a5d7b1ac.pdf), sometimes imputation can take a while. It would be very nice if there was a progress bar so that one can know whether it is stuck or just slow.

E.g. **readr** package displays a progress bar when running time is significant, but not otherwise. This is probably the best way to do it. It should probably be possible to disable by argument because in some contexts, getting a progress bar is undesired. For instance, in RNotebook files, progress bars result in the addition of a large number of new lines (every time it updates the bar).

My use case is that I am imputing two versions of a dataset (n=5920). One where variable types are mixed between ordinal and numeric, and one where they are all numeric (because they were corrected confounders using a linear model). I notice that the version with the mixed variables takes a lot longer to impute, several minutes, while the purely numerical version is quick to impute. Presumably this is because the calls to ordinal logistic regression are slow (see #7).

**Comment by alexkowa** [comment]
I do not see a straight forward way to include a progress bar in irmi, since it stops after an unknown number of steps (when convergence is reached). The easy thing would be to show a progress bar as a proportion of the maximal number of iterations, but this does not seem really useful.

**Comment by Deleetdk** [comment]
One could track the convergence, but the descent might not be linear and would thus be hard to convert to roughly linear progress bar.
