### ISSUE TITLE
irmi fails with data_frame with factors

### ISSUE THREAD

**Issue by Deleetdk** [statistikat/VIM#12]
This code causes an error when one uses a data_frame.

```
for(ind in indFac){
    if(length(levels(x[,ind]))==2)
      types[ind] <- "binary"
    else if(length(levels(x[,ind]))>2)
      types[ind] <- "nominal"
    else stop("factor with less than 2 levels detected!")
}
```

It's because you rely on the implicit automating dropping of a data frame to a vector that's done with the base R `data.frame`, but not with `data_frame`.

I'll write a fix for this small issue.

**Comment by alexkowa** [comment]
Thank you, I have manually applied your fix to the github version of VIM, because your pull request included files automatically generated by RStudio
