### ISSUE TITLE
update TF imputations variable in all imputation functions

### ISSUE THREAD

**Issue by alexkowa** [statistikat/VIM#28]

**Comment by GregorDeCillia** [comment]
@alexkowa The implementation of the TF columns seems fairly consistent in the current version of the package. Are you considering a refactoring in how these variables are represented? 

One idea for refactoring would be a new class `imputed_data_frame` which derives from `data.frame`. This would make it possible that the visualization functions could automatically detect those variables and show the imputed variables appropriately.

**Comment by alexkowa** [comment]
a new class seems to complicated. I like the current setup of just creating variables with a changeable suffix. So if this is implemented in all imputation functions we can probably close this issue?

**Comment by GregorDeCillia** [comment]
Yes, I agree that there would be quite some complexity added with a new class and the advantages are limited so far. We would have to add new features (like colored console output) to make this worthwhile. I'd also suggest to close this issue.
