### ISSUE TITLE
creating parallel processes in kNN_work function

### ISSUE THREAD

**Issue by Eitan177** [statistikat/VIM#29]
I'm wondering if turning the loop starting on line 262 of kNNFaster.R into a foreach loop (so that values of j can be submitted as parallel processes) would create undesired behavior. I think it will create different imputed values in the 'data' object since that object will not be updating every iteration though I don't know if this matters in regards to the accuracy of the imputation. Any thoughts would be appreciated!

**Comment by alexkowa** [comment]
- It should work straight forward for the case that all distance variables are completely observed.
- When missing valuesare in the distance variables and should be imputed in the processes, the option useImputedDist=TRUE would not work.

Anyways, the combine step must always just use the imputed variable j from each foreach process.

Are you having performance issues?
