### ISSUE TITLE
remove exports for VIMGUI

### ISSUE THREAD

**Issue by GregorDeCillia** [statistikat/VIM#37]
I wonder if the exports for the VIMGUI package are really necessary at this point. We have a block of code which seems only relevant for VIMGUI in `R/zzz.R` and some more in `R/utils.R`

Is VIMGUI still maintained? If so, should we move this functionality to that package?

https://github.com/statistikat/VIM/blob/d798d29357d25c8b2a017dbb24b5e52d01a57829/R/zzz.R#L30-L58

https://github.com/statistikat/VIM/blob/d798d29357d25c8b2a017dbb24b5e52d01a57829/R/utils.R#L146-L152

**Comment by alexkowa** [comment]
Good catch. Yes this can be removed. VIMGUI is archived.
