### ISSUE TITLE
remove stale branches

### ISSUE THREAD

**Issue by GregorDeCillia** [statistikat/VIM#43]
We currently have two stale branches in this repo for which I don't know if they are still needed

- [noroxy](https://github.com/statistikat/VIM/tree/noroxy) is behind master and probably marks the version just before roxygen2 was introduced to the VIM package. I suggest we either replace this with a tag or delete it completely.
- [mxnet](https://github.com/statistikat/VIM/tree/mxnet) contains 1 commit that introduces a new imputation algorithm using deep learning. Are there chances we might follow up on this in the future?

**Comment by alexkowa** [comment]
Yes, noroxy -> tag
For mxnet, I just very briefly experiemented, maybe we just keep it.
