### ISSUE TITLE
IRMI - too many (1830) weights

### ISSUE THREAD

**Issue by FilipaMarques** [statistikat/VIM#53]
Dear developers,

First of all let me thank you for all your work. I have implemented both hotdeck and knn with no problem at all and it was so easy. Thank you.
I am having a few problems with IRMI though. 
My dataset is a bit unusual, it has 243 observations and 332 variables, most variables are categorical and have around 30% to 50% missing values. Our goal is to study the impact of imputation on this kind of datasets.
When I try to run IRMI, by the 6th inner loop I get the following error:

> Error in nnet.default(X, Y, w, mask = mask, size = 0, skip = TRUE, softmax = TRUE,  : 
>   too many (1830) weights
> In addition: Warning messages:
> 1: In predict.lm(object, newdata, se.fit, scale = 1, type = ifelse(type ==  :
>   prediction from a rank-deficient fit may be misleading
> 2: glm.fit: algorithm did not converge 
> 3: In predict.lm(object, newdata, se.fit, scale = 1, type = ifelse(type ==  :
>   prediction from a rank-deficient fit may be misleading
> 4: glm.fit: algorithm did not converge 
> 5: In predict.lm(object, newdata, se.fit, scale = 1, type = ifelse(type ==  :
>   prediction from a rank-deficient fit may be misleading
> 6: In predict.lm(object, newdata, se.fit, scale = 1, type = ifelse(type ==  :
>   prediction from a rank-deficient fit may be misleading
> 7: glm.fit: algorithm did not converge 
> 8: In predict.lm(object, newdata, se.fit, scale = 1, type = ifelse(type ==  :
>   prediction from a rank-deficient fit may be misleading

From what I could find, one possible issue is the value of nnet.MaxNWts but after going through your source code I have realised this parameter is set to 50000 so it can't be the issue. 
Any thoughts?

Thank you
Filipa Marques

**Comment by matthias-da** [comment]
A guess:
R does not free the memory until it is closed (calling the garbage collector gc() does not help here, R really needs to be restartet. nnet() eats memory on every call.
I would either:
- compare the methods on a computer with more memory, or
- decrease the parameter value 50000
- stop after 3-4 iterations (maxit = 3)
Best
Matthias

**Comment by FilipaMarques** [comment]
Dear Matthias

I have decreased the maxit to 10 and then 3, both times the error was the
same and at the same "inner loop", the 6th.
From what I could understand, I was expecting to have the same error but
further along since more memory was available.
Since this did not happen, is it worth it to try the remaining suggestions
or is it safe to say the problem is not memory?

Best
Filipa Marques

Matthias Templ <notifications@github.com> escreveu no dia segunda,
28/09/2020 à(s) 09:57:

**Comment by matthias-da** [comment]
Dear Filipa

I'm still rather convienced that it is a memory issue, caused by nnet.

I would try to decrease the parameter value for nnet on the number of weights. 

Just to get sure: have you checked if all numeric, count or integer variables are stored as class "numeric" in your data set, and only the categorical variables are stored as class "factor". If one numeric variable is stored as factor, then you have a lot of classes that may also cause problems for nnet (and this is anyhow not useful).

Best
Matthias

**Comment by alexkowa** [comment]
It is not an memory issue per se, but a problem with your setup. Probably, there is a factor/character variable in your data set with a huge number of categories. Maybe you left the ID in it or something like that?

this is the reason for this kind of error message:
`
library(nnet)

## reasonable data set
d <- data.frame(x=rnorm(5000),y=rnorm(5000),k=sample(as.factor(1:18),5000,rep=TRUE))
m <- multinom(k ~ ., d)

## categorical variable with a lot of categories
d <- data.frame(x=rnorm(5000),y=rnorm(5000),k=sample(as.factor(1:500),5000,rep=TRUE))
m <- multinom(k ~ ., d)
`

**Comment by FilipaMarques** [comment]
The problem was indeed with the number of factors. 
Thank you
Filipa
