### ISSUE TITLE
Better support for ordered variables in kNN

### ISSUE THREAD

**Issue by alexkowa** [statistikat/VIM#57]
@merangelik can you check out the parameter ordFun in kNN, see commit https://github.com/statistikat/VIM/commit/e7e564f5748ecf20fb33d761515d3f10b4754938

**Comment by merangelik** [comment]
Can you please run roxygen2::roxygenise() or something similar? medianSamp is not exported and I think I do not have write permissions here

**Comment by alexkowa** [comment]
done.
