### ISSUE TITLE
Can I using irmi in parallel?

### ISSUE THREAD

**Issue by Bigsealion** [statistikat/VIM#58]
I want to impute my data by EM algorithm, so I using code `irmi(data)` in linux.
I want to know, is it run in parallel automatic? If the answer is yes, how do I control the number of CPU cores when it running?
Thanks!

**Comment by matthias-da** [comment]
The EM-algorithm irmi is an iterative approach whereby the next iteration always depends on the imputations/updates done in the previous one, thus such a kind of method is not suitable for parallel computing.

**Comment by Bigsealion** [comment]
> The EM-algorithm irmi is an iterative approach whereby the next iteration always depends on the imputations/updates done in the previous one, thus such a kind of method is not suitable for parallel computing.

Thanks for your reply! However, when I running `irim`, all of CPU core will be using. Is this necessary? Can I control the number of CPU cores that be occupied?
Thanks!

**Comment by matthias-da** [comment]
Hello,

are you sure, because the procedure can hardly be parallelised, and we do not call any library for parallel computing within irmi. Parallel computing is happening for calculations on my computer, and only one CPU is used when running irmi on my Mac.
