### ISSUE TITLE
hotdeck in version 6.1.0 crashes with message suggesting no donors

### ISSUE THREAD

**Issue by nalsalam** [statistikat/VIM#59]
Sorry, I can't provide a reprex.  I backed up to version 6.0.0 and everything works.  

In my application the first two below work but the third crashes:

%>% VIM::hotdeck(variable = "earnweek", domain_var = c("paidhour", "agecat15", "sex", "edcat", "race"))

%>% VIM::hotdeck(variable = "uhrswork1", domain_var = c("paidhour", "earnweek_cat", "edcat"))

%>% VIM::hotdeck(variable = "uhrswork1", donorcond = "<10", domain_var = c("paidhour", "earnweek_cat", "edcat"))

If I edit the 3rd to 

%>% VIM::hotdeck(variable = "uhrswork1", donorcond = "<10")

it works

I checked and there are always  more than one donor in the combinations of "paidhour", "earnweek_cat", and "edcat" when uhrswork1 < 10.   Sometimes only two donors but never zero which the error message implies. 

The error message to the best of my memory is zero replacement values in

  something[ ] <- something[ ]sample(something, 1)

**Comment by alexkowa** [comment]
Hi,
can you please confirm that the code below is giving the same error. So this is then a not caught error, but in this case it is caused by no available donors in some domains.
```
sleepI3 <- hotdeck(
   sleep,
   variable = c("NonD", "Dream", "Sleep", "Span", "Gest"),
   ord_var = "BodyWgt",
   domain_var = c("Pred","Exp"),
   donorcond = list(">4", "<17", ">1.5", "%between%c(8,13)", ">5")
)
```

**Comment by nalsalam** [comment]
Will do this evening.   Thanks for a great package and tool.

**Comment by nalsalam** [comment]
Yes, the above code produces the same error that I am getting with my code
and versions 6.1.0 and 6.1.1 (from a months ago)  but NOT with version 6.0.0

Error in Don[TFindex] <- Don[!TFindex][sample(sum(!TFindex), 1)] :
  replacement has length zero

And I now see that even though version 6.0.0 ran without error, not all
missing values were imputed.

In my opinion an error should not be generated when there are no available
donors, just a warning.
