### ISSUE TITLE
Ordered factors and malformed factors after kNN

### ISSUE THREAD

**Issue by lf-araujo** [statistikat/VIM#60]
Thank you for this software! kNN has been very useful in my work in the past!

I currently have to impute data in a dataset mainly composed of ordered factors, imputation works ok with mice. But then I decided to apply kNN. After imputation all variables have some rows with one long number (822083626) and this, it seems, is breaking the pipeline of analysis (an SEM comes after).

My code is very simple (working with tibbles, but tested with frames and tables):

```
id_dt <-
  kNN(d_dt,variable = c("pouco_interesse_fazer_coisas", "deprimido",
    "insonia_dormir_mais_costume",
    "cansado_pouca_energia", "falta_apetite_comendo_demais",
    "mal_consigo_mesmo", "dificuldade_concentracao",
    "lentidao_movimentar_agitado_inquieto",
    "pensar_se_ferir_morrer",
    "chronic_disease", "age_numeric", "disorder", "sex",
    "confinament", "assistance_mh", "physical_activity", "income"), k = 2, imp_var = FALSE)
```

`k = 2` is just to reduce processing time, while I figure the problem out.

![image](https://user-images.githubusercontent.com/10139950/114905866-d3239080-9def-11eb-9de7-1f57debf7648.png)

- What am I doing wrong? Should I toggle something to point to VIM which variables are ordinals?

Edit: VIM version 6.0.0.

Cheers

**Comment by alexkowa** [comment]
Hello,
I tried the following somehow replicating your problem, but this seems ok:

```
df <- data.frame(
  x=rnorm(100),
  y=rnorm(100),
  f1=as.factor(sample(LETTERS[1:4], 100, replace = TRUE)),
  o1=as.ordered(sample(LETTERS[1:3],100, replace = TRUE)),
  o2=as.ordered(sample(LETTERS[1:4],100, replace = TRUE)),
  o3=as.ordered(sample(LETTERS[1:5],100, replace = TRUE))
)
df[sample(1:nrow(df),10),"o1"] <- NA
df[sample(1:nrow(df),10),"o2"] <- NA
df[sample(1:nrow(df),10),"o3"] <- NA
dfi <-
  kNN(df,variable = c("o1","o2","o3"), k = 2, imp_var = TRUE)
```

can you provide a reproducible example?

**Comment by lf-araujo** [comment]
Thanks,

I believe it is something related to the version in my linux distro. Installed from github, restarted the session and the issue disappeared.

Thanks for the support.
