### ISSUE TITLE
Speed up implementation of kNN()

### ISSUE THREAD

**Issue by ag1805x** [statistikat/VIM#63]
Is there a way to speed up the implementation of kNN. I have a approx. 100 x 7000 matrix with about 3% missing values and it takes a long time to execute.

**Comment by matthias-da** [comment]
I do not think so. In any case, a k nearest neighbor approach might not be the best approach when having 7000 variables. I would rather think of a stepwise model-based imputation approach (e.g. `irmi()`) or using partial least squares or similar approaches for high-dimensional data.
