### ISSUE TITLE
MICE marginplot

### ISSUE THREAD

**Issue by Meg1512** [statistikat/VIM#64]
When using marginplot with NA data in MICE he three numbers at the lower left corner indicate the number of incomplete records for various combinations don't show up.

<img width="957" alt="Screen Shot 2021-11-04 at 4 07 38 pm" src="https://user-images.githubusercontent.com/93699473/140266449-bb7f63ea-8191-4396-8efd-f9f1f92ce502.png">

**Comment by aalfons** [comment]
It looks like there may not be enough space to display the numbers. Try using the argument `cex.numbers` to make them a bit smaller such that they have enough room to be displayed.

If this doesn't fix it, please provide us with a reproducible example such that we can look into it.

**Comment by Meg1512** [comment]
yep, thanks, that solved the problem.
