### ISSUE TITLE
Failed pkgdown Run

### ISSUE THREAD

**Issue by alexkowa** [statistikat/VIM#66]
Hi @GregorDeCillia,
it is not your package, but do you have an idea why the pkgdown won't work? Also locally, see https://github.com/statistikat/VIM/runs/4920454942?check_suite_focus=true 

Thy, Alex

**Comment by GregorDeCillia** [comment]
We might avoid this in the future if we use the roxygen tag `@family` to configure the reference index. This is already done with `@family imputation methods`
