### ISSUE TITLE
impPCA(), irmi(), kNN(), matchImpute(), medianSamp(), rangerImpute(), regressionImp(), sampleCat()

### ISSUE THREAD

**Issue by Shicheng-Guo** [statistikat/VIM#67]
I am wondering is there any script to compare the performance for these methods? impPCA(), irmi(), kNN(), matchImpute(), medianSamp(), rangerImpute(), regressionImp(), sampleCat()

Thanks. 

Shicheng

**Comment by alexkowa** [comment]
Do you mean performance as processing speed or accuracy of the estimation?

If you are looking for the fastest methods matchImpute should be first and hotdeck second, all the others it widely dependent on the setup.

For accuracy it is really hard to make general judgments.

So in fact for both the answer is "No". 

Be aware that medianSamp and sampleCat are not imputation functions itself but only helper functions for kNN to choose the imputed values from k donor values.
