### ISSUE TITLE
Remove documentation about metrics

### ISSUE THREAD

**Issue by NicGamb** [statistikat/VIM#76]
Hello,

First of all, thank you for this great package, which really helps me increase my datasets. 

I think perhaps you should remove "metric" from the documentation. I spent a significant amount of time looking for the alternatives and the default before finding out that all the R code is commented out and the method is implemented in C++ (I should have read the article first, before the doc),

Best regards,

**Comment by alexkowa** [comment]
Thank you for reporting this. Metric is not used for many years, so it should have been removed.
